import React from 'react';
import ReactDOM from 'react-dom';
import SeasonDisplay from './SeasonDisplay';
import Loader from './loader';







class App extends React.Component {

  /*
  alternate way to set state 
  js generated by babel upon getting state = {lat:null, error:''}
  constructor(props) {
    super(props)
    
    this.state = {lat:null, error:''};
  }
  */

  state = { lat: null, error: '' };

  componentDidMount() {
    window.navigator.geolocation.getCurrentPosition(
      position => {
        // only use setstate to change state
        this.setState({ lat: position.coords.latitude });
      },
      err => {
        this.setState({ error: err.message });
      }
    );
  }

  render() {
    if (this.state.error && !this.state.lat) {
      return <div>Error:{this.state.error}</div>;
    }
    if (!this.state.error && this.state.lat) {
      return <SeasonDisplay lat={this.state.lat} />;
    }
    return <Loader text="please allow the location" />

  }
}

ReactDOM.render(
  <App />,
  document.getElementById('root')
);